/****Script for global variable******/
var developerMode = false;
var globalDeviceType="";
var CURRENT_IP = document.domain;
var globalMAINCONFIG = [];
var globalInfoType = 'JSON'// XML or JSON
var loc = window.location.pathname;
var dir = loc.substring(0, loc.lastIndexOf('/'));
var canvasPage=0;
var TimeOut='';
var globalSanityFeature = "";
var devSanFlag = false;
var accSanFlag = false;
var connSanFlag = false;
var linkSanFlag = false;
var enableFlagSan = false;
var SanityFlag = false;
var subChannel = false;
var globalFlag = false;
var globalFlagCommitted = false;
var globalApplyAll = "deactive";
var imgArray = [];
var idsArray = [];
var checkLCArray = []; // holds all connected devices for checking
var pairedDevice='';
var linkcounter = 0;
var imgYPos=24;
var imgXPos=152;
var clearGrid = false;
var LoadImageFlag = false;
var LoadConfigFlag = false;
var Application="";
var autoTriggerTab = true;
var checkFromSanity = false;
var saveConfigFlag = false;
var saveImageFlag = false;
var saveresmain = "";
var ChatMax = true;
/*** DYNAMIC VARIABLES FOR CONFIG EDITOR ***/
var portMapInfo = new Array();
var dynamicManagePortArr = ["managePortArr"];
var dynamicLineConnected = ["lineConnected"];
var dynamicLineConnected2 = ["lineConnected2"];
var dynamicResourceId = ["ResourceId"];
var dynamicTopology = ["Topology"];
var dynamicMainId = ["MainId"];
var dynamicFlagCommitted = ["globalFlagCommitted"];
var dynamicVar = ["stage_0"];
var dynamicLayer = ["layer"];
var dynamicLine = ["redLine"];
var dynamicTipLayer = ["tooltipLayer"];
var dynamicToolTip = ["tooltip"];
var dynamicMinimap = ["ministage_0"]; // for minimap
var dynamicMiniLayer = ["layer"];
var dynamicZoomOrigin = ["zoomOrigin"];
var dynamicZoomFactor =  ["zoomFactor"];
var dynamicPinchLastDist = ["pinchLastDist"];
var dynamicPinchStartCenter = ["pinchStartCenter"];
var dynamiclayerScale = ["layerScale"];
var dynamiclayerOffsetX =["layerOffsetX"];
var dynamiclayerOffsetY = ["layerOffsetY"];
var dynamicRect = ["rect"];
var dynamicDebug = ["Debug"];
var dynamicDomain = ["Domain"];
var dynamicOtherUser = ["User"];
var pageCanvas = 0;
var globalManageDeviceShow = "";
var TimePicker = true;
var StartReservation= "false";
var EndReservation="false";
var autoDDevLists=[];
var autoDDevData=[];
var autoDDomainOptions="";
var autoDCurIdx = -1;
var saveAutoDDevNode = [];
var autoDPartnerSlots = [];
var editDevInfoAdmin = false;
var editedDevInfoAdmin = [];
var editedDevInfoPerTabAdmin = [];
var availParPortsAdmin = {};
var partSlotsEditDevice = [];
var globalLinkAction = "";
var gblCondition = "";
var AnotherUser="";
var Commit="true";
window['variable' + dynamicLineConnected[pageCanvas]] = [];
window['variable' + dynamicLineConnected2[pageCanvas]] = [];
var loadConfigName = '';
var dynamicGreenRouletteArr= ['greenRouletteArr'];
window['variable' + dynamicGreenRouletteArr[pageCanvas]]=[];
var fromNavigator = "";
var globalscale = 1;
/****varibale for main config *****/
var GlobalSlotID = "";
var GlobalPortIP = "";
var GlobalNewDevice = [];
var GlobalMedia = "";
var globalTabId = "";
var conterninfor = [];
var ConnectivityFlag= ["ConnectivityFlag"];
var enablePort = false;
var ResourceId="";
var DomainName="";
var Connectivity="";
var testToolObj = [];
var DeviceSanity="";
var AccessSanity="";
var ZoneName="";
var DebugMode="false";
var RedFlag="";
var FileType="";
var LinkSanityEnable="";
var PortMappingEnable="";
var CommitEnable="";
var Iteration="";
var Interval="";
var MainId="";
var MainConfigurationUserId="";
var Name="";
var userInformation = [];
var globalUserName,globalUserId;
var DateTime="";
var IterList="";
var IterNumber="";
var Offset="";
var DST="1";
var ResourceOrig="";
var ReservationType="Now";
var DevListFlag="";
var DevListCtr="";
var DndCtr="";
var TopologyName="";
var FileType="";
var UserName="";
var portmapArr = [];
var portmapNameArr = [];
var stage;
var layer;
var tooltipLayer;
var globalIPV4Flag = false;
var enDisFilter=true;
var enDisTimepicker=true;
var enDisMode=false;
var StartOfReservationInfoForImage={};
var StartOfReservationInfoForConfig={};
var EndOfReservationInfoForImage={};
var EndOfReservationInfoForConfig={};
var globalReciever = "";
var MyRefresh;
var PowerDeviceCon = [];
var PowerImageCon = [];
var LoadImageEnable = "false";
var LoadConfigEnable = "false";
var SaveImageEnable = "false";
var SaveConfigEnable = "false";
var PowerLoadImage = [];
var CurSanityRunning = [];
var GlobalSlotId = "";
var GlobalModuleId = "";
var PopUpLoader = "<center><div><img src='img/ajax-loader.gif'/></div></center";
var AutoDType="";
/****varibale for device *****/
var sourcePath = "";
var dstPath = "";
if(globalInfoType == "XML"){
	var devicesArr = [];
	var deviceArr = [];
	var rackArr = [];
	var devip4vArr = [];
	var slotArr = [];
	var moduleArr = [];
	var picArr = [];
	var portArr = [];
	var portArr2 = [];
}
var deviceCtr = 1;
var lineConnected = []; // hold all paired/connected devices
var lineNameArr=[];
var lineSpeed="";
var lineName="";
var lineType="";
var ZoneDomain="";
var gblCanvasWidth="", gblCanvasHeight;
var portflag = false;
var portflag2 = false;
var portspeedflag = false;
var portspeedflag2 = false;
var connectedSwitch = false;
var sourceSwitch = "";
var destSwitch = "";
var trashW,trashH;
var glblDevMenImg,gblDevMenY,gblDevMenX;
var gblLinkSource,gblLinkDestination;
var titanVar ="",topoMapVar ="";
var globalConfgName=[],globalConfgId=[];
var devicesUpFlagObj=[];
var rackUpFlagObj =[];
var slotUpFlagObj =[];
var moduleUpFlagObj =[];
var portUpFlagObj =[];
var picUpFlagObj =[];

var updateFlagSet = [];
/****data before commit****/
if(globalInfoType == "XML"){
	var devicesArrBC = [];
	var deviceArrBC = [];
	var rackArrBC = [];
	var slotArrBC = [];
	var moduleArrBC = [];
	var picArrBC = [];
	var portArrBC = [];
}
var lineConnected2 = []; // hold all paired/connected devices
//after commit
if(globalInfoType == "XML"){
	var deviceArrAC =[];
	var devicesArrAC = [];
	var devPathArr=[];
	var rackArrAC = [];
	var rackPathArr = [];
	var slotArrAC = [];
	var slotPathArr = [];
	var moduleArrAC = [];
	var modulePathArr =[];
	var picArrAC = [];
	var picPathArr = [];
	var portArrAC = [];
	var portPathArr =[];
	var portmapArrAC = [];
}
var lineConnectedAC = [];
var lineNameArrAC =[];
var devicesUpArr = [];
var rackUpArr =[];
var slotUpArr =[];
var moduleUpArr =[];
var picUpArr =[];
var portUpArr=[];
/***Resource Management***/
var loader = "<tr style='height:35em;'><td colspan='30' stlye='text-align:center;'>Processing Information... <br /><img src='img/ajax-loader.gif'/></td></tr>";	
var changeStructure;
var devdev1;
var eventid1;
var statsstats;
var eventid;
var SanityId;
var SanityName;
var SanityDevId;
var globalHostName;
var globalDeviceId;
var configname;
var split = "";
split = new Date().toString().split(" ");
var x = split[5].toString();
var timezone = "";
timezone = x.substring(3);
var globalResourceId = [];
var globalPageRM;
var genIds = [];
var scheventid = [];
var deviceHistoryId = [];
var mainConfigHistoryId = [];
var DeviceId = [];
var ResId = "";
var deviceType = [];
var startDate = [];
var StartDate = new Array();
var Priority = new Array();
var TimeInterval = new Array();
var Recurrence = new Array();
var StartTime = new Array();
var EndDate = new Array();
var EndTime = new Array();
var DeviceReservation = new Array();
var Hosts = new Array();
var str = "";
var autoRefresh;	
var showMoreInfo = 20;	
var	globalDevArr = [];
var	globalIterArr = [];
var	globIter = "";
var	globDev = "";
var	globalReservationInfo = {};
var	globalPageIter = {};
var tableClass = "";
var OSArray = new Array();
var OSVerArray = new Array();
var SWArray = new Array();
var nameArray = new Array();
var ProdArray = new Array();
var VerArray = new Array();
var RouteNameArray = new Array();
var RouteProdArray = new Array();
var RouteVerArray = new Array();
var EmbNameArray = new Array();
var EmbProdArray = new Array();
var EmbVerArray = new Array();
var LineNameArray = new Array();
var LineProdArray = new Array();
var LineVerArray = new Array();
var ModNameArray = new Array();
var ModProdArray = new Array();
var ModVerArray = new Array();
var BWArray = new Array();
var TypeArray = new Array();
var EncaArray = new Array();
var FilterHolder = new Array();
var globalStrFilter = '';
var globalStrFilter2 = '';
var globalStrFilter3 = '';
var globalStrFilter4 = '';
var globalStrFilter5 = '';
var globalStrFilter6 = '';
var globalFiltArray = {};
var prevDomainVal = "";
var PortId = [];
var RMLoadObject = [];
var StartImgArr = [];
var StartConArr = [];
var EndImgArr = [];
var EndConArr = [];
var startimagedetail = "false";
var startconfigdetail = "false";
var endimagedetail = "false";
var endconfigdetail = "false";
var setvaluesstartimage = false;
var setvaluesstartconfig = false;
var setvaluesendimage = false;
var setvaluesendconfig = false;
var globalTTPorts = {};

var globalSaveImagePrimary = {};
var globalSaveImageSecondary = {};
var globalSaveImageCustom = {};
var globalSaveConfigPrimary = {};
var globalSaveConfigSecondary = {};
var globalSaveConfigCustom = {};
var globalSaveImageDetailPrimary = {};
var globalSaveImageDetailSecondary = {};
var globalSaveImageDetailCustom = {};
var globalSaveConfigDetailPrimary = {};
var globalSaveConfigDetailSecondary = {};
var globalSaveConfigDetailCustom = {};
var globalLoadImagePrimary = {};
var	globalLoadImageSecondary = {};
var	globalLoadImageCustom = {};
var	globalLoadConfigPrimary = {};
var	globalLoadConfigSecondary = {};
var	globalLoadConfigCustom = {};
var	globalLoadImageDetailPrimary = {};
var	globalLoadImageDetailSecondary = {};
var	globalLoadImageDetailCustom = {};
var	globalLoadConfigDetailPrimary = {};
var	globalLoadConfigDetailSecondary = {};
var	globalLoadConfigDetailCustom = {};

/*View Options*/
var viewconfigname = true;
var viewhostname = true;
var viewmanagementip = true;
var viewconsoleip = true;
var viewloopbackadd = true;
var viewosversion;
var viewsoftwarepack;
var viewinterfaceip = true;
var viewinterfacename = true;
/***** ACTION *******/
var globalLAdate; 
var globalLArId;
var globalLAFlag = false;
var devicesFilter = [];
/*** FILTER ***/
var systemsname2='Any';
var productId2='Any';
var vId2='Any';
var ostype2= 'Any';
var osversion2= 'Any';
var swpackage2 = 'Any';

var speed2 = '';
var portname = '';
var mediatype2 = '';
var bandwidth2 = '';

var HostName;
/*Logs*/
var DevName;
/*History*/
var msg;
/*Statistics and Reports*/
var globalStatSelect = 'Device';
var globalViewStatSelect = 'Detailed';
var globalStatsViewNew = 'Utilization';
var globalStatsView = 'daily';
var globalDomainContent = 'Any';
var globalDate = '';
var globalStatPage = '1';
var globalStatLimit = '20';
var globalSwitch = 'no';
var globalTerminal = 'no';
var globalStatFilter = '';
var globalFilStatCom = '';
var globalFilStatData = '';
var globalstatlimit = '20';
var globalstatpage  = '1'
var globaldate = '';
//var fileview = 'csv';
var statId = [];

/* ADMINISTRATION */
var globalUserLoad = "";
var globalAddUserPolIds = new Array();
var globalSelectedAdminMain = new Array();
var globalUserDomainIds = new Array();
var globalUserDomainNames = new Array();
var globalUserZoneIds = new Array();
var globalUserZoneNames = new Array();
var globalUserGroupIds = new Array();
var globalDynamicSelected = new Array();
var globalAdminPage = "";
var pagelimit = 10;
var globalName = "";
var globalDesc = "";
var accRiAction = "";
var accRiEntity = "";
var globalAdminFunc = "";
var PerPage=1;
var TotalRowData;
var CurrentPage;
var TotalPages;
var prev;
var next;
var GlobalPageType;
var globalDeviceInformationTab=new Array();
var globaleviceInformationJSON;
var globalPageAdmin;
var globalUserIdArray = [];
var globalAdminGroupId = [];
var globalResourceGroupId = [];
var userGroupFlag = [];
var globalUserGroupId = [];
var globalUsersIdArray = [];
var globalUserNameArray = [];
var globalUserNamesArray = [];
var globalUserGroupName = [];
var globalUGroupPolicyIds = new Array();
var globalDomainBoundUserIds = new Array();
var globalUserPolicyIds = new Array();
var globalUserPolicy2Ids = new Array();
var globalAddBindedUser = [];
var globalAddDevice = [];
var globalRemoveDevice = [];
var globalDevBoundDomIds = new Array();
var globalDomDevIds = new Array();
var globalDomDev2Ids = new Array();
var addedCountry = [];
var deletedCountry = [];
var addedCompany = [];
var deletedCompany = [];
var globalDPSFlag = "";
var globalDomDPS2Ids = new Array();
var globalDomDPSIds = new Array();
var globalAccActiveStatus = [];
var globalAccInactiveStatus = [];
var globalDomActiveStatus = [];
var globalDomInactiveStatus = [];
var globalDPSBoundIds = [];
var loadDAFlag = "";
var globalPrevDomainAdminArray = new Array();
var globalCurrDomainAdminArray = new Array();
/* POWER MANAGEMENT */
var globalCIP = new Array();
var pmpage = "";
var PMDeviceId = '';
var outletBinding = [];
var selectedOutletPower = "";
var PMip = [];

/* AUTO DISCOVERY */
var initAutoD;
var autoDcomplete = false;
/* Open Console*/
var sessionId = "";
var setInt = "";
var globalRefresh = false;
var consoleNotificationFlag = false;
var typeID = "";
var validDevices = [];
var validSessionDevices = [];
var seletedSessionId = [];
var seletedSessionTabArray = [];
var userExistArray = [];
var userNotExistArray = [];
/* MAP LINK */
var globalY = 0;
var globalY2 = 0;
var ReleaseFlagLoadActive = false;

/*----HISTORY GLOBAL-----*/
window['variableHistory'+pageCanvas] = new Array();
autoRefreshLogs = "";

/*---Check Power ON, OFF Cycle ---*/
var powerDevices=[];
var powerDevices2=[];
var powerOutletTableObj = {};
var powerDEVICES = [];
var powerDevicesState=[];
var selectedInlet = {};

